In [1]:
# Quick start

import numpy as np
x = np.array([1, 2, 6, -3, 0, 5, -4])
x

array([ 1,  2,  6, -3,  0,  5, -4])

In [2]:
# Simple numpy.array math

print(x + 1)
print(x * 3)

[ 2  3  7 -2  1  6 -3]
[  3   6  18  -9   0  15 -12]


In [3]:
# Useful functions

print(np.arange(10))
print(np.linspace(0, 1, 11))
print(np.logspace(0, 5, 6))
print(np.pi)
print(np.e)
print(np.log10(2))
print(np.sin(np.pi/6))

[0 1 2 3 4 5 6 7 8 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]
3.141592653589793
2.718281828459045
0.3010299956639812
0.49999999999999994


In [4]:
# Matrices

x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print(x.shape)
print(x.ndim)
print(x.size)
print(x.dtype)
print(x.T)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int32
[[1 4]
 [2 5]
 [3 6]]


In [5]:
# array methods example

print(x.max())
print(np.max(x))

6
6


In [6]:
# Vectorization

r = np.arange(10) * 10
print(r[1:])
print(r[::-1])
print(r[[0, 2, 8, 1]])
print(r[ r > 55 ])

[10 20 30 40 50 60 70 80 90]
[90 80 70 60 50 40 30 20 10  0]
[ 0 20 80 10]
[60 70 80 90]


In [7]:
# Random data and matrix algebra

y1 = np.int64(np.random.random([2, 3]) * 10)
y2 = np.int64(np.random.random([2, 3]) * 10)
print(y1)
print(y2)
print(y1 + y2)
print(y1 * y2)

[[3 1 5]
 [6 7 1]]
[[6 7 4]
 [5 3 4]]
[[ 9  8  9]
 [11 10  5]]
[[18  7 20]
 [30 21  4]]


In [8]:
# Saving and loading to binary strings

x = np.arange(8, 0, -1, dtype=np.int16)
blob = x.tostring()
y = np.fromstring(blob, dtype=np.int16)
print(blob)
assert (x == y).all()

b'\x08\x00\x07\x00\x06\x00\x05\x00\x04\x00\x03\x00\x02\x00\x01\x00'


c:\users\elibo\.virtualenvs\adv-python-course-dtvwex1r\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """


The `scipy` package has much more useful algorithms, including:
- linear algebra methods (least-squares fitting)
- differential equations solvers
- numerical optimization
- FFT
- signal processing (DSP)
- statistics
- image processing

Please look at http://docs.scipy.org/doc/scipy/reference/tutorial/index.html